services:
  caddy:
    image: docker.io/caddy:2.10.2-alpine
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy-conf:/etc/caddy
      - caddy-data:/data
      - caddy-config:/config

  influxdb2:
    image: influxdb:2
    container_name: influxdb
    restart: always
    hostname: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: $INFLUXDB_USERNAME
      DOCKER_INFLUXDB_INIT_PASSWORD: $INFLUXDB_PASSWORD
      DOCKER_INFLUXDB_INIT_ORG: $INFLUXDB_ORG
      DOCKER_INFLUXDB_INIT_BUCKET: $INFLUXDB_BUCKET
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: $INFLUXDB_ADMIN_TOKEN
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

  grafana:
    image: grafana/grafana-enterprise
    user: "1000"
    depends_on:
      - influxdb2
    container_name: grafana
    restart: always
    ports:
      - 8088:3000
    environment:
      INFLUXDB_DATA_INDEX_VERSION: "tsi1"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,\
                          grafana-influxdb-08-datasource,\
                          grafana-kairosdb-datasource,\
                          grafana-piechart-panel,\
                          volkovlabs-form-panel, \
                          grafana-simple-json-datasource"
      GF_PLUGINS_PREINSTALL: "influx-adecwatts@/tmp/grafana-plugins/influx-adecwatts.zip"
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_PASSWORD
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-plugins:/tmp/grafana-plugins

volumes:
  caddy-data:
  caddy-config:
  influxdb2-data:
  influxdb2-config:
  grafana-data: